# Generated by Django 4.2.4 on 2023-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0023_userdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="birthday",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="city",
            field=models.CharField(default="Kisumumakemi", max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="country",
            field=models.CharField(default="Kenya", max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="gender",
            field=models.CharField(default="Male", max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="occupation",
            field=models.CharField(default="Developer", max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="phone",
            field=models.CharField(default="0703991583", max_length=200),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="street",
            field=models.CharField(default="Nyalenda", max_length=200),
        ),
    ]
